### Cadastrar Livro - POST
POST http://localhost:5231
Content-Type: application/json
{
    "titulo" : "Chave do Sucesso",
    "categoria" : {"id" : 1}
}

### Listar Livros - GET ALL
GET http://localhost:5231/api/livros

### Listar Livro por Id - GET by ID
GET http://localhost:5231/api/livros/1

### Atualizar Livro - PUT 
PUT http://localhost:5231/api/livros/1
Content-Type: application/json
{
    "titulo" : "Mais esperto que o diabo",
    "categoria" : {"id" : 2}
}

### Remover Livro - DELETE
DELETE http://localhost:5231/api/livros/1